# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_pic',
            new_name='profile_pic',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_site',
            new_name='profile_site',
        ),
    ]
